services:

    _defaults:
        public: false

    Yarhon\LinkGuardBundle\Annotations\Parser:
        arguments:
            - '@annotation_reader'

    Yarhon\LinkGuardBundle\Security\Provider\SymfonyAccessControlProvider: ~

    Yarhon\LinkGuardBundle\Security\Provider\SensioSecurityProvider:
        arguments:
            - '@Yarhon\LinkGuardBundle\Annotations\Parser'

    Yarhon\LinkGuardBundle\Security\AccessMap:
        arguments:
            - '@router.default'
            - '@kernel'

    Yarhon\LinkGuardBundle\Security\Authorization\AuthorizationManager:
        arguments:
            - '@Yarhon\LinkGuardBundle\Security\AccessMap'
            - '@security.authorization_checker'

    Yarhon\LinkGuardBundle\CacheWarmer\RouteCacheWarmer:
        arguments:
            - '@Yarhon\LinkGuardBundle\Security\AccessMap'
            - null
        tags: ['kernel.cache_warmer']

    Yarhon\LinkGuardBundle\DependencyInjection\Compiler\UrlGeneratorConfigurator:
        arguments:
            - '@Yarhon\LinkGuardBundle\Security\Authorization\AuthorizationManager'
            - null

    Yarhon\LinkGuardBundle\Twig\Extension\RoutingExtension:
        arguments:
            - { referenceVarName: route_reference }
        tags: ['twig.extension']

    Yarhon\LinkGuardBundle\Twig\RoutingRuntime:
        arguments:
            # services should go here
