build:
    environment:
        php: { version: '7.2' }

    tests:
        override:
            - vendor/bin/simple-phpunit

    nodes:
        coverage:
            tests:
                override:
                    -   command: 'vendor/bin/simple-phpunit --coverage-clover=coverage.xml'
                        coverage:
                            file: 'coverage.xml'
                            format: 'clover'
        tests_php_71:
            environment:
                php: { version: '7.1' }

        tests_php_70:
            environment:
                php: { version: '7.0' }

        tests_php_56:
            environment:
                php: { version: '5.6' }

        tests_php_56_lowest:
            environment:
                php: { version: '5.6' }
            dependencies:
                override:
                    - composer install --no-interaction --prefer-lowest --prefer-stable

        tests_php_55:
            environment:
                php: { version: '5.5' }

filter:
    excluded_paths:
        #- Tests/*

