build:
    environment:
        php: { version: '7.2' }

    dependencies:
        after:
            - composer require phpunit/phpunit:^7.0||^6.0||^5.2 --dev

    tests:
        override:
            - vendor/bin/phpunit

    nodes:
        coverage:
            tests:
                override:
                    -   command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                        coverage:
                            file: 'coverage.xml'
                            format: 'clover'

        tests_php_71:
            environment:
                php: { version: '7.1' }

        tests_php_70:
            environment:
                php: { version: '7.0' }

        tests_php_56:
            environment:
                php: { version: '5.6' }

        tests_php_56_lowest:
            environment:
                php: { version: '5.6' }
            dependencies:
                override:
                    - composer update --no-interaction --prefer-lowest --prefer-stable

filter:
    excluded_paths:
        #- Tests/*