build:
    environment:
        php: { version: '7.2' }

    dependencies:
        before:
            - composer require phpunit/phpunit:^7.0 --dev

    nodes:
        coverage:
            tests:
                override:
                    -   command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                        coverage:
                            file: 'coverage.xml'
                            format: 'clover'
        tests_php_71:
            environment:
                php: { version: '7.1' }

#            dependencies:
#                after:
#                    - composer require phpunit/phpunit:^5.2||^6.0||^7.0 --dev --no-interaction

        tests_php_70:
            environment:
                php: { version: '7.0' }

        tests_php_56:
            environment:
                php: { version: '5.6' }

        tests_php_56_lowest:
            environment:
                php: { version: '5.6' }
            dependencies:
                override:
                    - composer update --no-interaction --prefer-lowest --prefer-stable

filter:
    excluded_paths:
        #- Tests/*